spring:
  datasource:
    url: jdbc:postgresql://db:1999/api
    username: postgres
    password: example

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        forma_sql: true

application:
  jwt:
    secretKey: securesecuresecuresecuresecuresecuresecuresecuresecsecuresecuresecuresecuresecuresecuresecuresecuresecure
    tokenPrefix: "Bearer "
    tokenExpirationAfterDays: 14
  filesystem:
    path: C:\Users\Daan\WebstormProjects\void-hub\api\files