spring:
  datasource:
    url: jdbc:postgresql://db:1999/api
    username: postgres
    password: example

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        forma_sql: true